foodordering/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<p>',views.add_to_cart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('removefromcart/<p>', views.remove_from_cart, name="removefromcart"),
    path('deletefromcart/<p>', views.delete_from_cart, name="deletefromcart"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview")

]

foodordering/foodordering/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls'))

]
if settings.DEBUG:
   urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

foodordering/search/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from search import views
app_name="search"
urlpatterns = [
path('search',views.search,name="search")
]

foodordering/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
     path('',views.allcategories,name="allcat"),
     path('allproducts/<p>',views.allproducts,name="allproducts"),
     path('viewproduct/<p>',views.viewproduct,name="viewproduct"),
     path('register/',views.register,name="register"),
     path('login/',views.user_login,name="login"),
     path('logout/', views.user_logout, name="logout"),
]

foodordering/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    noofitems= models.IntegerField()
    address= models.TextField()
    phone=models.CharField(max_length=30)
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status = models.CharField(max_length=30,default="pending")
    date_ordered=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class Account(models.Model):
    accnum=models.CharField(max_length=30)
    acctype = models.CharField(max_length=30)
    amount=models.IntegerField()
    def __str__(self):
        return self.accnum

foodordering/search/models.py
from django.db import models

# Create your models here.

foodordering/shop/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    image = models.ImageField(upload_to='shop/categories', blank=True, null=True)
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    image = models.ImageField(upload_to='shop/products', blank=True, null=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

foodordering/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart,Account,Order
def cartview(request):
    total = 0
    u=request.user

    try:
        cart=Cart.objects.filter(user=u)
        for i in cart:
            total += i.quantity * i.product.price

    except:
        pass
    return render(request,'cart.html',{'c':cart,'total':total})
@login_required
def add_to_cart(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=product)
        if(cart.quantity<cart.product.stock):
           cart.quantity+=1
           cart.save()
    except:
        cart=Cart.objects.create(product=product,user=u,quantity=1)
        cart.save()
    return redirect('cart:cartview')

@login_required
def remove_from_cart(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=product)
        if(cart.quantity!=0):
            cart.quantity-=1
        else:
            pass
        cart.save()
    except:
        cart=Cart.objects.remove(user=u,product=product)
        cart.save()

    return redirect('cart:cartview')

@login_required
def delete_from_cart(request,p):
    product=Product.objects.get(name=p)
    u=request.user
    cart=Cart.objects.get(user=u,product=product)
    cart.delete()

    return redirect('cart:cartview')

def orderform(request):
    if(request.method=='POST'):
      a=request.POST['a']
      p=request.POST['p']
      n=request.POST['n']
      u=request.user
      cart=Cart.objects.filter(user=u)

      total = 0
      for i in cart:
            total += i.quantity * i.product.price

      ac=Account.objects.get(accnum=n)
      if(ac.amount>=total):
          ac.amount=ac.amount-total
          ac.save()

          for i in cart:  #create record in order table for each object in Cart table for the current user
              o=Order.objects.create(user=u,product=i.product,address=a,phone=p,noofitems=i.quantity,order_status="paid")
              o.save()
              i.product.stock=i.product.stock-i.quantity
              i.product.save()
          cart.delete()    #clears the cart items for the current user
          msg="Order Placed Successfully"
          return render(request,'orderdetail.html',{'m':msg})
      else:
          msg="Insufficient Amount in User Account. You cannot place the order."
          return render(request, 'orderdetail.html', {'m': msg})

    return render(request,'orderform.html')

def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o})

foodordering/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def search(request):
    q=""
    product=None
    if(request.method=="POST"):
        q=request.POST['q']
        if q:
            product=Product.objects.filter(Q(name__icontains=q))
    return render(request,'search.html',{'p':product,'query':q})

foodordering/shop/views.py
from django.shortcuts import render
from shop.models import Category,Product
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'category':c})
def allproducts(request,p):
    b=Category.objects.get(name=p)
    product=Product.objects.filter(category=b)
    return render(request,'product.html',{'c':b,'p':product})

def viewproduct(request,p):
    c=Product.objects.get(name=p)
    return render(request,'viewproduct.html',{'product':c})

def register(request):
        if (request.method == "POST"):
            u = request.POST['u']
            p = request.POST['p']
            cp = request.POST['cp']
            e = request.POST['e']
            if (p == cp):
                u = User.objects.create_user(username=u, password=p, email=e)
                u.save()
                return user_login(request)
            else:
                return HttpResponse("password not matching")
        return render(request, 'register.html')

def user_login(request):
    if (request.method == "POST"):
        name = request.POST['u']
        pass1 = request.POST['p']  # here we mentioned as pass1 because pass is a keyword
        user = authenticate(username=name, password=pass1)
        if user:
            login(request,user)
            return allcategories(request)
        else:
            messages.error(request, 'invalid credentials')
    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

foodordering/templates/base.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>FOOD LOGO</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="icon" href="{% static 'images/food_logo.jpg' %}"type="image/x-icon">
</head>
<body id="bg" style="background-image:url('{% static "images/img1.jpg" %}');background-repeat:no-repeat;background-size:100%;background-position:center;background-attachment:fixed;" >
<header>
   <center> <img src="{% static 'images/food_logo.jpg' %}" style="width:100px;height:100px;margin-top:10px;margin-bottom:10px;"></center>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid" style="background-color:#a1d7f0;">
    <a class="navbar-brand" href="#">FOOD LOGO</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>
            {% endfor %}
          </ul>
        </li>

          {% if user.is_authenticated %}
          {% if user.is_superuser == False %}
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping" ><sub>{{count}}</sub></i></a>
          </li>
         <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'cart:orderview' %}">Order View</a>
        </li>
        {% endif %}
          <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
        {% else %}
          <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>

        {% endif %}
      </ul>

      <form class="d-flex" method="POST" action="{% url 'search:search' %}" style="background-color:black;">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}
<footer>
    <div class="footer">
        <i class="fa-regular fa-copyright"></i>&nbsp;Food Logo Pvt ltd.All Rights Reserved</div>
</footer>
</body>
</html>

foodordering/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if not c %}
<div>
    <h3 class="text-center">Cart is Empty</h3>
    <h5 class="text-center text-success"><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h5>
</div>
{% else %}
<div class="container-fluid ">
<div class="row">
    <h4 class="text-center fw-bold mt-2">SHOPPING CART</h4>
    <div class="col-sm-6" >
        <table class="table table-bordered" style="margin-bottom:60px;background-color:#a1d7f0;">
            <tr><th colspan="5" class="text-center" >CARD ITEMS</th></tr>
            {% for i in c %}
            <tr>
                <td><img src="{{ i.product.image.url}}" height="150px" width="150px"></td>
                <td><b>{{i.product.name}}</b></td>
                <td><b> Product id :{{i.product.id}}</b><br>
                    <b> Product Price :{{i.product.price}}</b><br>
                    <b> Quantity :{{i.quantity}} * {{i.product.price}}</b></td>
                <td><b>Subtotal:{{i.subtotal}}</b></td>

                <td>
                    {% if i.quantity < i.product.stock %}
                    <b><a href="{% url 'cart:addtocart' i.product.name %}"><i  style="color:black;"  class="fa-solid fa-circle-plus"></i></a>
                    <a href="{% url 'cart:removefromcart' i.product.name %}"><i  style="color:black;"  class="fa-solid fa-circle-minus"></i></a>
                    <a href="{% url 'cart:deletefromcart' i.product.name %}"><i  style="color:black;" class="fa-solid fa-trash"></i></a></b>
    {% else %}
                     <b><a href="{% url 'cart:removefromcart' i.product.name %}"><i  style="color:black;"  class="fa-solid fa-circle-minus"></i></a>
                    <a href="{% url 'cart:deletefromcart' i.product.name %}"><i  style="color:black;" class="fa-solid fa-trash"></i></a></b>
                </td>
            </tr>
            {% endif %}
    {% endfor %}
        </table>

    </div>
    <div class="col-sm-6 " >
        <table class="table table-bordered" style="background-color:#a1d7f0;">
            <th class="text-center">CHECK OUT</th>
            <tr><td><b>TOTAL:{{total}}</b></td></tr>
        </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-outline-primary"><b>Place Order</b></a>
        <a href="{% url 'shop:allcat' %}" class="btn btn-outline-primary" style="position:absolute;right:40px"><b>Continue Shoping</b></a>

    </div>
</div>
    </div>
{% endif %}
{% endblock %}

foodordering/templates/category.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>

  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/Chinese.jpg' %}" width="100%"   height="650px" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/Italian.jpg' %}" width="100%" height="650px" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/indian1.jpg' %}" width="100%" height="550px" alt="...">
    </div>
      <div class="carousel-item">
      <img src="{% static 'images/Mexican.jpg' %}" width="100%" height="550px" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<div class="container" style="margin-top:20px;text-align:center;">
  <h2 style="font-weight:bold;">Online Food Ordering</h2>
    <p style="text-align:justify;background-color:#a1d7f0;"><b>Food Logo food delivery is a largest online service for online food delivery.
      Traditional food delivery services have long been a part of the food industry, with local restaurants and fast-food chains offering home delivery or takeout options.[18] These services often rely on in-house or third-party delivery drivers who transport prepared meals directly from the restaurant to the customer. Dominos, Pizza Hut, and Papa John's are examples of established global brands that have been offering delivery services for decades.</b></p>
</div>
<div class="container rounded">
  <div class="row">
    {% for i in category %}
    <div class="col-lg-6">
      <div class="card border border-dark " style="width:20rem;height:630px;margin-bottom:60px;margin-left:75px;">
  <img src="{{i.image.url}}"  height="350px" class="card-img-top border border-dark" alt="...">
  <div class="card-body">
    <h5 style="font-weight:bold;text-align:center;" class="card-title">{{i.name}}</h5>
    <p style="text-align:justify;background-color:#a1d7f0;" class="card-text">{{i.desc}}</p>
    <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-secondary" style="position:relative;left:73px;" >View Menu</a>
  </div>
</div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

foodordering/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center><h1> Login Here</h1></center>
<center>
    <form method="POST" >
        {% csrf_token %}
  <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"   placeholder="Enter the Password">
</div>
        <input type="submit" class="form-control" value="submit">

        </form>

    {% if messages %}
    {% for i in messages %}
    <ul>
        <li>{{i}}</li>
    </ul>
    {% endfor %}
    {% endif %}
</center>
{% endblock %}

foodordering/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3">
    <center>
        <h3 class="fw-bold">{{m}}</h3>
        <h5 class="text-success">Thank You....</h5>
    </center>
</div>

{% endblock %}

foodordering/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center><h1> Order Details</h1></center>
<center>
    <form method="POST" >
        {% csrf_token %}
  <div class="mb-3">
  <label  class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the address">
  </div>
  <div class="mb-3">
  <label  class="form-label">Phone</label>
  <input type="number" class="form-control" name="p"   placeholder="Enter the Phone number">
  </div>
  <div class="mb-3">
  <label  class="form-label">Account Number</label>
  <input type="number" class="form-control" name="n"   placeholder="Enter the Account number">
  </div>
        <input type="submit" class="form-control" value="submit">

        </form>

{% endblock %}

foodordering/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h4 class="mt-3">Name of Customer :{{user}}</h4>

    {% for i in o %}
    <div class="row  border">
        <div class="col-sm-4 mt-3">
            <img src="{{i.product.image.url}}" height="200" width="400">
        </div>
        <div class="col-sm-4" style="font-size:18px;background-color:#a1d7f0;">
            <p>Order Address:{{i.address}}</p>
            <p>Customer Phone:{{i.phone}}</p>
            <p>Product Name:{{i.product.name}}</p>
            <p>Product Price:{{i.product.price}}</p>
            <p>Ordered on:{{i.date_ordered}}</p>
            <p>Delivery Status:{{i.delivery_status}}</p>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

foodordering/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<br>
<div>
    <h3 align="center" style="background-color:#b5e0e8">{{c.name}}</h3>
  <img  src="{{c.image.url}}" height="600px" width="100%" >
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;text-transform: uppercase;">

  <p style="linne-height:1.8;text-align:justify;background-color:#a1d7f0;">{{c.desc}}</p>

  <div class="row">

      {% for i in p %}
    <div class="col-lg-6">

            <div class="card" style="width:20rem; margin-bottom:60px;margin-left:90px;">

  <img src="{{i.image.url}}" class="card-img-top p-2" alt="..." style="height:200px;">
  <div class="card-body">
    <h5 class="card-title text-center" style="font-weight:bold;">{{i.name}}</h5>
      <br>
    <p class="card-text text-center"> PRICE: {{i.price}}</p>
          <a href="{% url 'shop:viewproduct' i.name %}" class="btn btn-secondary" style="position:relative;left:36%;">Details</a>
  </div>
</div>
        </div>

  {% endfor %}
  </div>
</div>
{% endblock %}

foodordering/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
<h1> Registartion Details</h1>
    <form method="POST" style="margin-bottom:100px;">
        {% csrf_token %}
  <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter the username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"   placeholder="Enter the Password">
</div>
        <div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter password again">
</div>
      <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter email">
</div>
       <input type="submit" class="form-control" value="submit">

        </form>
</center>
{% endblock %}

foodordering/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block content %}
<center>
  <div class="text-center">
    <h4>You have Searched For <span class="text-danger fw-bolder">{{query}}</span></h4>
  </div>
</center>
<div class="container mt-2 rounded rounded-5" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-lg-4">

            <div class="card" style="width: 20rem; margin-bottom:60px; margin-top:50px;">

  <img src="{{i.image.url}}" class="card-img-top p-2" alt="..." style="height:200px; margin-top:40px;">
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <p class="card-text text-center">{{i.price}}</p>
          <a href="{% url 'shop:viewproduct' i.name %}" class="btn btn-primary" style="position:relative;left:34%;">Details</a>
  </div>
</div>
        </div>
      {% empty %}
      <h4 class="text-center text-danger">No Search Results Found</h4>
{% endfor %}
    </div>

</div>

{% endblock %}

foodordering/templates/viewproduct.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<div class="row">
  <div class="col-2 m-5" ">
    <center><img src="{{product.image.url}}" class="card-img-top" alt="..." style="width:100%;" height="300"></center>

  </div>
  <div class="col-sm-6 mt-5" style="text-transform: uppercase;font-size:20px;background-color:#a1d7f0;">

        <h5>Name : {{product.name}}</h5>
      <p><b>Stock : {{product.stock}}</b></p>
        <p >Description : {{product.desc}}</p>
        <h5>Price : {{product.price}}</h5>
        {% if user.is_superuser == False %}
            {% if p.stock <= 0 %}
                <h5 class="text-danger">Out Of Stock</h5>
            {% else %}
                <a   class="btn btn-outline-primary" href="{% url 'cart:addtocart' product.name %}">ADD TO CART</a>
            {% endif %}
        {% else %}
            {% if product.stock <= 0 %}
                <h5 class="badge bg-danger text-dark" s>Out Of Stock</h5><br>
                <a   class="btn btn-outline-success" href="{% url 'admin:index' %}">ADD  STOCK</a>
            {% else %}

                <a   class="btn btn-outline-success" href="{% url 'admin:index' %}">ADD  STOCK</a>
            {% endif %}
        {% endif %}
  </div>
</div>
{% endblock %}